---
- hosts: all
  become: yes
  become_user: root
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - calvinbui.ansible_datadog
  vars:
    datadog_api_key: DD_API_KEY
    datadog_config:
      tags:
        - env:dev
      logs_enabled: true
      process_config:
        enabled: "true"

